#!/bin/bash

HOMEDIR=$HOME

OUTF=college-wsgiapp-aliases.conf
COLLEGE_DIR=$HOMEDIR/Development/codes/isu-enterprise/college
COLLEGE_ASSET_DIR=$COLLEGE_DIR/isu.college/src/isu/college/templates
WEBAPP_DIR=$COLLEGE_DIR/isu.webapp/src/isu/webapp
WEBAPP_ASSET_TEMPL=$WEBAPP_DIR/templates
WEBAPP_ASSET_LTE=$WEBAPP_DIR/admin-lte

echo "Output goes to $OUTF"

echo "#This file was generated by $0 script." > $OUTF
echo "#DO NOT EDIT IT, JUST RUN IT AGAN." >> $OUTF
echo "Alias /lcss $COLLEGE_ASSET_DIR/lcss">> $OUTF
echo "Alias /js $WEBAPP_ASSET_TEMPL/js" >> $OUTF
echo "Alias /bootstrap $WEBAPP_ASSET_LTE/bootstrap" >> $OUTF
echo "Alias /plugins $WEBAPP_ASSET_LTE/plugins" >> $OUTF
echo "Alias /dist $WEBAPP_ASSET_LTE/dist" >> $OUTF



